server:
  port: 8081

spring:
  application:
    name: isa-user
  data:
    mongodb:
      host: localhost
      port: 27017
      database: isa1
      auto-index-creation: true

logging:
  level:
    org.springframework: DEBUG
  file:
    name: /tmp/logs/${spring.application.name}.log